server: 
  port: 8080
postgres: 
  host: "localhost"
  port: 54321
  database: "saas-be-usergroup"
  user: "postgres"
  password: "password"
redis: 
  host: "localhost"
  port: 63791
  password: ""
jwt:
  access_secret: "9991fdc97dc1dfcb5fe1348c8acd580bb2f130a838b2ba908577c83f77bb3ef9"
  refresh_secret: "9991fdc97dc1dfcb5fe1348c8acd580bb2f130a838b2ba908577213h5wdfd4"